№1

Напишите функцию, которая классифицирует фильмы из материалов занятия по правилам:
Оценка 2 и ниже — низкий рейтинг;
Оценка 4 и ниже — средний рейтинг;
Оценка 4.5 и 5 — высокий рейтинг.
Результат классификации запишите в столбец class.

In [10]:
import pandas as pd

In [5]:
move = pd.read_csv('C:/Users/sanar/Desktop/ml-latest-small/ml-latest-small/movies.csv')
move.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [7]:
rating = pd.read_csv('C:/Users/sanar/Desktop/ml-latest-small/ml-latest-small/ratings.csv')
rating.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [9]:
join = rating.merge(move, on='movieId', how='left')
join.head()

,userId,movieId,rating,timestamp,title,genres
0,1,31,2.5,1260759144,Dangerous Minds (1995),Drama
1,1,1029,3.0,1260759179,Dumbo (1941),Animation|Children|Drama|Musical
2,1,1061,3.0,1260759182,Sleepers (1996),Thriller
3,1,1129,2.0,1260759185,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller
4,1,1172,4.0,1260759205,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama

In [13]:
def ocenka(rat):
    if rat >= 4.5:
        return 'высокий рейтинг'
    elif rat > 2 and rat <= 4:
        return 'средний рейтинг'
    else:
        return 'низкий рейтинг'

In [17]:
join['class'] = join['rating'].apply(ocenka)
join.head()

,userId,movieId,rating,timestamp,title,genres,class
0,1,31,2.5,1260759144,Dangerous Minds (1995),Drama,средний рейтинг
1,1,1029,3.0,1260759179,Dumbo (1941),Animation|Children|Drama|Musical,средний рейтинг
2,1,1061,3.0,1260759182,Sleepers (1996),Thriller,средний рейтинг
3,1,1129,2.0,1260759185,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller,низкий рейтинг
4,1,1172,4.0,1260759205,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama,средний рейтинг

№2

Нужно написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определённому региону. Т. е. если поисковый запрос содержит название города региона, то в столбце ‘region’ пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим ‘undefined’.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

geo_data = {'Центр': ['москва', 'тула', 'ярославль'],
'Северо-Запад': ['петербург', 'псков', 'мурманск'],
'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']}

Результат классификации запишите в отдельный столбец region.

In [12]:
keywords = pd.read_csv('C:/Users/sanar/Desktop/ml-latest-small/ml-latest-small/keywords.csv')
keywords.head()

         keyword     shows
0             вк  64292779
1  одноклассники  63810309
2          порно  41747114
3           ютуб  39995567
4      вконтакте  21014195

In [14]:
def geo(key):
    if 'москва' in key:
        return 'Центр'
    elif 'тула' in key:
        return 'Центр'
    elif 'ярославль' in key:
        return 'Центр'
    elif 'петербург' in key:
        return 'Северо-Запад'
    elif 'псков' in key:
        return 'Северо-Запад'
    elif 'мурманск' in key:
        return 'Северо-Запад'
    elif 'владивосток' in key:
        return 'Дальний Восток'
    elif 'сахалин' in key:
        return 'Дальний Восток'
    elif 'хабаровск' in key:
        return 'Дальний Восток'
    else:
        return 'undefined'

In [16]:
keywords['region'] = keywords['keyword'].apply(geo)
keywords.head()

         keyword     shows     region
0             вк  64292779  undefined
1  одноклассники  63810309  undefined
2          порно  41747114  undefined
3           ютуб  39995567  undefined
4      вконтакте  21014195  undefined

In [18]:
keywords = keywords[keywords['region'].isin(['Северо-Запад', 'Дальний Восток', 'Центр'])]
keywords.head()

                        keyword   shows          region
127                авито москва  979292           Центр
370    авито ру санкт петербург  425134    Северо-Запад
564   погода в санкт петербурге  292489    Северо-Запад
849             авито ярославль  209581           Центр
1063        фарпост владивосток  176951  Дальний Восток